version: '3.8'
######################this is the correct file
services:
  # PostgreSQL for authentication
  auth-db:
    image: postgres:17
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth123
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    networks:
      - healthcare-net

  # PostgreSQL for admin
  admin-db:
    image: postgres:17
    environment:
      POSTGRES_DB: admin_db
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: admin123
    volumes:
      - admin-db-data:/var/lib/postgresql/data
    networks:
      - healthcare-net

  # PostgreSQL for doctor
  doctor-db:
    image: postgres:17
    environment:
      POSTGRES_DB: doctor_db
      POSTGRES_USER: doctor_user
      POSTGRES_PASSWORD: doctor123
    volumes:
      - doctor-db-data:/var/lib/postgresql/data
    networks:
      - healthcare-net

  # Eureka Server
  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    environment:
      - EUREKA_INSTANCE_HOSTNAME=eureka-server
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - healthcare-net

  # Authentication Service
  auth-service:
    build: ./authentication-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://auth-db:5432/auth_db
      - SPRING_DATASOURCE_USERNAME=auth_user
      - SPRING_DATASOURCE_PASSWORD=auth123
      - JWT_SECRET=mySecretKeyForJWTGenerationWithAtLeast32CharactersLong
      - JWT_EXPIRATION=3600000
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - auth-db
      - eureka-server
    networks:
      - healthcare-net

  # Admin Service
  admin-service:
    build: ./admin-service
    ports:
      - "8088:8088"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://admin-db:5432/admin_db
      - SPRING_DATASOURCE_USERNAME=admin_user
      - SPRING_DATASOURCE_PASSWORD=admin123
      - INTERNAL_API_KEY=your-secret-internal-key
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - admin-db
      - eureka-server
    networks:
      - healthcare-net

  # API Gateway
  api-gateway:
    build: ./api-gateway
    ports:
      - "8089:8089"          # host:container
    environment:
      - JWT_SECRET=mySecretKeyForJWTGenerationWithAtLeast32CharactersLong
      - JWT_EXPIRATION=3600000
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - auth-service
      - admin-service
      - eureka-server
    networks:
      - healthcare-net

  aisymptom-service:
    image: 2002rusira/aisymptomservice:v2
    ports:
      - "8098:8098"
    environment:
      - PORT=8098
      - INTERNAL_API_KEY=your-secret-internal-key
      - GEMINI_KEY=AIzaSyDoEwx8LaiED2SVuhQPNo9gOVXrZGY9NJM
      - EUREKA_SERVER=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      - api-gateway
    networks:
      - healthcare-net

  # Doctor Service
  doctor-service:
    build: ./doctor-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://doctor-db:5432/doctor_db
      - SPRING_DATASOURCE_USERNAME=doctor_user
      - SPRING_DATASOURCE_PASSWORD=doctor123
      - INTERNAL_API_KEY=your-secret-internal-key
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      - doctor-db
    networks:
      - healthcare-net


networks:
  healthcare-net:
    driver: bridge

volumes:
  auth-db-data:
  admin-db-data:
  doctor-db-data:

