server:
  port: 8088

spring:
  application:
    name: admin-service
  datasource:
    url: jdbc:postgresql://localhost:5432/admin_db
    username: postgres
    password: 20021021@Rusira
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

internal:
  api:
    key: your-secret-internal-key

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}