server:
  port: ${PORT:8098}
spring:
  application:
    name: aisymptom-service

internal:
  api:
    key: ${INTERNAL_API_KEY:your-secret-internal-key}

gemini:
  api:
   key: ${GEMINI_KEY}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://eureka-server:8761/eureka/}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}