server:
  port: 8096

spring:
  application:
    name: aisymptom-service

internal:
  api:
    key: your-secret-internal-key

gemini:
  api:
    key: AIzaSyBnXOHNef_C392wxtyAzHp3JLPFeGDbDrg

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}