server:
  port: 8090

spring:
  application:
    name: aisymptom-service

jwt:
  secret: mySecretKeyForJWTGenerationWithAtLeast32CharactersLong
  expiration: 3600000

internal:
  api:
    key: your-secret-internal-key

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}